server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hidesuwa
    url: jdbc:mysql://8.138.228.106:3306/cloud_classroom
    # 配置数据库连接池 Hikari 连接池
    hikari:
      minimum-idle: 3
      # 自动提交
      auto-commit: true
      # 最大连接数
      maximum-pool-size: 5
      # 连接最大存活时间
      connection-timeout: 30000
      # 空闲超时时间
      idle-timeout: 600000
      # 最大存活时间
      max-lifetime: 1800000
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 8.138.228.106
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    password: hidesuwa

logging:
  file:
    path: /usr/local/cloud_classroom/cloud_classroom_logs

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否从 Cookie 读取 Token
  is-read-cookie: false
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

file:
  filepath: /usr/local/cloud_classroom/file/
  pdf: /usr/local/cloud_classroom/file/pdf/
  video: /usr/local/cloud_classroom/file/video/
  word: /usr/local/cloud_classroom/file/word/
  ppt: /usr/local/cloud_classroom/file/ppt/
  filePic: /usr/local/cloud_classroom/file/filePic/
  networkPath: /cloudClassroom/api/file/

  #图片保存路径
image:
  courseIcon: /usr/local/cloud_classroom/file/image/courseIcon/
  pre: http://8.138.228.106:8089/cloudClassroom/api/file/image/