server:
  port: 8089
  servlet:
    context-path: /cloudClassroom/api
spring:
    profiles:
      active:
        '@env@'
    servlet:
      multipart:
        max-file-size: 500MB
        max-request-size: 500MB